### ISSUE TITLE
Support for Multiple EditText with one emojiButton

### ISSUE THREAD

**Issue by eltos** [hani-momanii/SuperNova-Emoji#11]
When using multiple `EditText` in an Activity, it is impossible to insert emojies in both `EditText`.
When changing the focus from one to another `EditText`, emojies are still inserted in the one that was passed to the `EmojIconActions` constructor.

Please add support for multiple `EditText`!!!

**Comment by hani-momanii** [comment]
@eltos Added in commit [Add Multi editText support](https://github.com/hani-momanii/SuperNova-Emoji/commit/cb1af9871d1b965532e352153eb56afeedf4fc29)
You can add many  edit texts using this method:
`public void addEmojiconEditTextList(EmojiconEditText... emojiconEditText)`
