### ISSUE TITLE
Both emoji and keyboard open at same time

### ISSUE THREAD

**Issue by deepakandroiddeveloper** [hani-momanii/SuperNova-Emoji#13]
hey guys i was using your library from two months.it was working fine but now from two days when i click on the emoji icon to open emoji pop up both emoji pop up and key boards open at the same time. can u please help me out.

**Comment by hani-momanii** [comment]
@deepakandroiddeveloper  can you provide the android version and device model, Thanks.

**Comment by deepakandroiddeveloper** [comment]
@hani-momanii android version is 7.0 and device is nexus six .

**Comment by deepakandroiddeveloper** [comment]
@hani-momanii  and when i m implement this library again in the new prjct, always keyboard opens on the smiley icon click emoji pop doesn't open.
