### ISSUE TITLE
Estimation of library size?

### ISSUE THREAD

**Issue by pellyadolfo** [hani-momanii/SuperNova-Emoji#15]
I started integrating this library in my app but I quit when I realised of the size added to the app is about 5M. My app is 3.5M and increasing 5M just because emoji is oversized.

Can you please confirm this fact? Any way to reduce library size and estimation of final size?

On the other hand, adding 

    compile 'hani.momanii.supernova_emoji_library:supernova-emoji-library:0.0.2'

to my code did not hep to compile the library so I needed to download the files as a zip.

**Comment by hani-momanii** [comment]
@pellyadolfo yes, the library size big, and this issue fixed and the release is soon,
 You need to add: 
`repositories {
    maven { url "https://dl.bintray.com/hani-momanii/maven"}
}`

To get the library,

**Comment by shashank26ashu** [comment]
Hey thanks for library just want to know any update on fixing library size ?

**Comment by hani-momanii** [comment]
check the last version please 

```
compile 'com.github.hani-momanii:SuperNova-Emoji:1.1'
```

**Comment by hani-momanii** [comment]
#24 Fix this problem
