### ISSUE TITLE
double click it in the first time to get show emoji's

### ISSUE THREAD

**Issue by idanbar134** [hani-momanii/SuperNova-Emoji#16]
Hi,

When I open the activity for the first time and try to open the emoji's I have to tap the button twice.
do you know why it's happens?

Thanks,
Idan

**Comment by hani-momanii** [comment]
this is strange, the first tap open the normal keyboard ?

**Comment by awaistoor** [comment]
Hi, I have the same issue, any solution? 
The issue is when I open the activity, I have to double tap the emoji button to show the emoji keyboard. By default, I am not calling ShowEmojIcon() and added it on the emoji button's on click.
Thankyou

**Comment by bhoomikaPrajapati** [comment]
Hello,I have Same issue.
Emoji open on Double tap on First time only.
please provide me Solution.

Thank you.

**Comment by obaidjatoi** [comment]
Hello , Thanks for the library, and yes i am also facing same issue on some devices and that is on some devices if we click on emoji button , both keyboards are opened at same time, Emoji on upper side of text keyboard..
