### ISSUE TITLE
Not Convert emoji to unicode 

### ISSUE THREAD

**Issue by amit016verma** [hani-momanii/SuperNova-Emoji#17]
Sir, I need your help, please sort out from this issue 
I am converting emoji to 
String toServerUnicodeEncoded = StringEscapeUtils.escapeJava(message);

with the help of this compile 'org.apache.commons:commons-lang3:3.4' dependency
but its not working

**Comment by hani-momanii** [comment]
`StringEscapeUtils.escapeJava(edittext.getText().toString());` to get it in unicode format.

**Comment by amit016verma** [comment]
thanks for replying

**Comment by amit016verma** [comment]
Hi,
I nned your help if I want to setText of EmojiconEditText then is it
possible to show the emoji in that edit text plz reply me and thanks in
advance
