### ISSUE TITLE
Can you help me in the following?

### ISSUE THREAD

**Issue by YasirAmeen** [hani-momanii/SuperNova-Emoji#19]
First of all thanks for your library its great, but i am facing very strange problem.

On server side, i have datatype for image is **utf8mb4** 
i am sending emoji to user using chat application. 

he and me can say emojis first time, but whenever we close app and open chat screen again. all the emojis i send converted to ud3ud8udccud etc without / (slash) 

i also tried EmojitTextView for chat bubbles.

Thanks
Regards
Yasir Ameen

**Comment by hani-momanii** [comment]
Do you store the messages locally ? 
if you send him emoji it shown on your device correct, nut when he receive it dose he see it right ?

**Comment by YasirAmeen** [comment]
no i am not storing messages locally, and yes first time when i sent emoji it shows correct but when we close the app and come again to the chat screen (android app fetch all the messages into ArrayList) and shows emojis converted to ud343 etc etc with / slash

**Comment by hani-momanii** [comment]
what Unicode used on the  remote DB?

**Comment by hani-momanii** [comment]
You should use utf8mb4  charset  instead of utf8, check your DB.
[https://mathiasbynens.be/notes/mysql-utf8mb4](Read this)
