### ISSUE TITLE
emojiAlignment parameters doesn't work,

### ISSUE THREAD

**Issue by grestuccia1** [hani-momanii/SuperNova-Emoji#2]
emojiAlignment parameters doesn't work, multiline text with android:lineSpacingExtra="7sp"

![screen shot 2016-05-16 at 10 32 46 pm](https://cloud.githubusercontent.com/assets/5777472/15308672/28acebd0-1bb6-11e6-8517-419ebe0f1f7f.png)

**Comment by hani-momanii** [comment]
@eltos Added in commit [Fix alignment](https://github.com/hani-momanii/SuperNova-Emoji/commit/3849ee1da5601010e1c43eaf7f97af88550e6fea)
