### ISSUE TITLE
My Android Studio can't open project SuperNova-Emoji-master

### ISSUE THREAD

**Issue by afaideen** [hani-momanii/SuperNova-Emoji#22]
Here the image what it returns...

![image](https://cloud.githubusercontent.com/assets/12533089/24506907/9ae165b6-1591-11e7-87db-2d4606b9ec95.png)

**Comment by hani-momanii** [comment]
remove this tow lines:
`apply plugin: 'com.jfrog.bintray'
apply plugin: 'com.github.dcendents.android-maven'`
