### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by bala3493** [hani-momanii/SuperNova-Emoji#28]
In 'HOT BEVERAGE' tap one emoji icon was missed. It showing 9749 string instead of that emoji icon. I have attached screenshot of this bug.
![emoji_icon](https://cloud.githubusercontent.com/assets/8123969/26407718/82f31abe-40b9-11e7-855b-176c30e4833a.png)

**Comment by hani-momanii** [comment]
Use the latest Version 
`compile 'com.github.hani-momanii:SuperNova-Emoji:1.1'`
