### ISSUE TITLE
Emoji keyboard opening instead of normal keyboard

### ISSUE THREAD

**Issue by activesince93** [hani-momanii/SuperNova-Emoji#32]
When `emojIcon.setUseSystemEmoji(true);` is there and clicked on editText, emoji keyboard is opening instead of normal keyboard. It should open emoji keyboard only when clicked on emoji icon. Same behaviour is there for `emojIcon.setUseSystemEmoji(false);`.

When commenting `emojIcon.setUseSystemEmoji(true);` works well, but I want to display system emojis only.

**Comment by MohamedWael** [comment]
@activesince93  have you solved your problem?

**Comment by activesince93** [comment]
I set the default value of `private boolean useSystemEmoji = true` in `EmojIconActions ` file. It is working for me now.

**Comment by MohamedWael** [comment]
thanks, i solved my problem by setting ```emojIcon.ShowEmojIcon();``` in the click listener of the emoji button
