### ISSUE TITLE
Calling EmojiconTextView.setText() is causing the RecyclerView to lag whilst it's scrolling

### ISSUE THREAD

**Issue by Meeks91** [hani-momanii/SuperNova-Emoji#4]
If I call `EmojiconTextView.setText() ` whilst the RecyvlerView is scrolling the RecyclerView lags, but when I use the same data set and replace the EmojiconTextViews with TextViews the RecyclerView doesn't lag whilst is scrolling, so it seems that  calling `EmojiconTextView.setText()` whilst the RecyclerView is scrolling is the cause of the RecyclerView lagging while it's scrolling.

**Comment by Max01010101010101** [comment]
How can we fix this lag.. hum i want to use this lib

**Comment by yakuzaaaa** [comment]
Any solution ?

**Comment by hani-momanii** [comment]
Try changing the view holder class to static one , that will improve the performance

**Comment by stefi92** [comment]
It doesn't helped to me. Any other solutions?
